# Generated by Django 5.2.8 on 2025-11-30 20:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossarioCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('termo_tecnico', models.CharField(help_text='Ex: Budget, Churn, ASAP', max_length=200, unique=True)),
                ('explicacao_simples', models.TextField(help_text='Explicação em linguagem clara e acessível.')),
                ('exemplo_uso', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Ex: Financeiro, TI, Siglas', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaliseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto_original', models.TextField()),
                ('texto_sugerido_ia', models.TextField(blank=True, help_text='Versão reescrita para ser mais inclusiva')),
                ('vies_detectado', models.BooleanField(default=False)),
                ('explicacao_vies', models.TextField(blank=True, help_text='Explicação pedagógica do viés encontrado')),
                ('foi_enviado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_enviados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('deficiencia', models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('AUDITIVA', 'Auditiva / Surdez'), ('VISUAL', 'Visual / Baixa Visão'), ('MOTORA', 'Motora'), ('INTELECTUAL', 'Intelectual / Neurodivergente'), ('OUTRA', 'Outra')], default='NENHUMA', max_length=20, verbose_name='Tipo de Deficiência')),
                ('preferencia_comunicacao', models.CharField(choices=[('TEXTO', 'Texto / Chat (Assíncrono)'), ('LIBRAS', 'LIBRAS (Língua de Sinais)'), ('LEITURA_LABIAL', 'Vídeo com Foco Labial'), ('AUDIO', 'Áudio / Voz')], default='TEXTO', max_length=20, verbose_name='Preferência de Comunicação')),
                ('bio_resumida', models.TextField(blank=True, help_text='Breve descrição para vitrine de talentos.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReuniaoAcessivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Reunião')),
                ('data_reuniao', models.DateTimeField(verbose_name='Data e Hora')),
                ('arquivo_audio', models.FileField(blank=True, null=True, upload_to=core.models.audio_upload_path, verbose_name='Gravação (MP3/WAV)')),
                ('transcricao_completa', models.TextField(blank=True, verbose_name='Transcrição Literal (Whisper)')),
                ('resumo_executivo', models.TextField(blank=True, verbose_name='Ata Inteligente (GPT)')),
                ('pontos_destaque', models.JSONField(blank=True, default=dict, verbose_name='Atribuição de Créditos')),
                ('status_ia', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando IA...'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro no Processamento')], default='PENDENTE', max_length=20)),
                ('participantes', models.ManyToManyField(related_name='reunioes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
